[tool.poetry]
name = "fibo-testpypi2"
version = "0.2.0"
description = "A class to calculate fibonacci numbers"
authors = ["e60e256 <e60nayuta@g.ecc.u-tokyo.ac.jp>"]
readme = "README.md"
license = "BSD-3-Clause"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
